name: Tests

on:
  pull_request:
    branches: [main]
    paths:
      - 'back/**'
      - '.github/workflows/tests.yml'
      - '.github/workflows/phpunit.yml'

jobs:
  phpunit:
    uses: ./.github/workflows/phpunit.yml
